views/wcq/coach/coach.pug
views/wcq/coach/matches.pug

Also fixed links for unplayed matches

Fixed Sorting of matches

---

server.js

Added static route for let's encrypt

Let's encrypt

---

views/accountlayout.pug
views/layout.pug
views/signup/signup-existing.pug
views/signup/signup-new-coach.pug
views/signup/signup-reroll.pug

GDPR complaince

---

lib/signupService.js
robots.txt
server.js

don't overwrite email and steam

---

areas/signup/signup.js

Rerolling for existing teams didn't work correctly anymore, because I tried to fix something else ...
99 small bugs in the code
99 small bugs
take 1 down
patch it around
103 small bugs in the code

Signup bug fixed

---

areas/maintenance/maintenance.js
lib/CyanideService.js
package-lock.json
package.json
server.js

Dropped async-request in favour of axios. Less dependencies, no npm warnings about older packages it used.
Dropped connect-nedb-session in favour of nedb-session-store, which hopefully solves somes session issues.

axios & nedb-session-store

---

areas/signup/signup.js
views/signup/signups.pug

Turned cache back on

---

areas/account/account.js
areas/api/v1/greenhorn.js
areas/api/v1/signups.js
areas/api/v1/standings.js
areas/coach/coach.js
areas/maintenance/maintenance.js
areas/rebbl/coach.js
areas/rebbl/division.js
areas/rebbl/league.js
areas/rebbl/match.js
areas/rebbl/stunty.js
areas/rebbl/team.js
areas/signup/signup.js
areas/wcq/coach.js
areas/wcq/match.js
areas/wcq/round.js
areas/wcq/wcq.js
lib/CyanideService.js
lib/signupService.js
lib/teamservice.js
lib/util.js
views/accountlayout.pug
views/coachlayout.pug
views/layout.pug
views/signup/overview.pug

:white_check_mark: Removed greenhorn signup
:white_check_mark: Added Confirm button
:white_check_mark: Added team check
:white_check_mark: cleaned up code

Added confirm and teamcheck

---

views/coach/coach.pug

because <@182485585137631233> and <@97434597427535872> started complaining

lower case reddit name

---

lib/LeagueService.js
views/layout.pug
views/rebbl/league/index.pug

Dropdown order reversed for season
Sorting (10 before 2) fixed
Season 9 default selected

Standings improvementes

---

areas/account/account.js
areas/maintenance/maintenance.js
areas/rebbl/coach.js
areas/rebbl/team.js
lib/LeagueService.js
lib/bloodbowlService.js
lib/signupService.js
lib/teamservice.js
public/styles/style.css
views/coachlayout.pug
views/rebbl/coach/coach.pug
views/rebbl/coach/team.pug
views/rebbl/team/player.pug
views/rebbl/team/playerstats.pug
views/rebbl/team/team.pug

Now you can view teams of the coach. Not optimal yet, but I want the sync of the data live

Added teams

---

areas/rebbl/match.js
lib/LeagueService.js
views/rebbl/division/matches.pug
views/rebbl/league/index.pug
views/rebbl/match/match.pug

Link to team from standings,
Link to team from match report
Link to coach from match report
Added unplayed match view from fixture that matches /account/match

More links to teams

---

lib/teamservice.js
views/rebbl/division/index.pug
views/rebbl/division/round.pug
views/rebbl/league/index.pug
views/rebbl/team/team.pug

Also, on demand of <@271855364645847041> fixed proper natural sorting.

Fixed caching issue

---

areas/maintenance/maintenance.js
lib/teamservice.js

Team sync is going to be set up on a 2 hour schedule

Fixed team sync

---

lib/LeagueService.js

Fudged a regular expression

---

areas/rebbl/match.js
views/rebbl/match/match.pug
views/rebbl/match/player.pug
views/rebbl/match/team.pug
views/rebbl/match/teamoverview.pug
views/rebbl/team/player.pug
views/rebbl/team/team.pug

Added SPP progress to Match report and Team pages.
Added player level to team page
Adjusted match TV with value of journeyman

Displaying SPP

---

lib/teamservice.js
views/rebbl/team/team.pug

Added Team's motto to team page

Fixed team sync issue

---

views/rebbl/match/player.pug
views/rebbl/match/teamoverview.pug
views/rebbl/team/player.pug

Legendary players where displayed with 192/undefined SPP's

Added "*" as a level

---

lib/teamservice.js

https://rebbl.net/rebbl/team/866385 or https://rebbl.net/rebbl/team/Âlve  now produce the same page

Add possibility to use team name over team id

---

public/styles/style.css
views/rebbl/division/index.pug

browsing to https://rebbl/Gman/Season 9 - Division 2#7 now fully displays the week

Fixed offset for anchors

---

lib/LeagueService.js

Finally figured out the cache issue

---

views/rebbl/league/index.pug

Instead of using jQuery to do it

 default hide seasons that are inactive

---

views/account/match.pug
views/layout.pug

CSS through CDN

---

views/layout.pug

💰💰💰💰💰💰💰
💴💴💴💴💴💴💴
💵💵💵💵💵💵💵
💶💶💶💶💶💶💶
💷💷💷💷💷💷💷
💳💳💳💳💳💳💳
¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤¤

SHOW ME THE MONEY!!!!!!!

---

areas/api/v1/upcoming.js
areas/rebbl/division.js
lib/DatingService.js
lib/LeagueService.js
views/account/match.pug
views/rebbl/division/index.pug
views/rebbl/division/matches.pug

Clock indicatotor on division overview for games that are scheduled.
Twitch link on "unplayed" matches

Dates everywhere!

---

views/rebbl/upcoming/index.pug

All off = show all.
Then toggle the ones you want to see instead of toggling the ones you don't want to see

Inverted how the filter works

---

areas/admin/user.js

Edit user for admins corrected

---

areas/api/v1/admin/strikes.js
areas/api/v1/admin/user.js
lib/accountService.js
views/admin/layout.pug
views/admin/strikes/index.pug
views/admin/user/user.pug
views/layout.pug
views/no-cache-sub-layout.pug

Moar dots! need moar dots!

---

lib/LeagueService.js

don't continue testing for [admin]-teams if the game is removed from the array

Fixed an issue for upcoming games

---

areas/signup/signup.js
lib/signupService.js

use EnsureLoggedIn instead of EnsureAuthenticated

New users don't have accounts yet

---

areas/admin/admin.js
areas/admin/contest.js
areas/api/v1/admin/admin.js
areas/api/v1/admin/contest.js
lib/LeagueService.js
lib/util.js
views/admin/contest/index.pug

 Added possibility to correct games 

---

areas/rebbl/team.js
lib/bloodbowlService.js
lib/teamservice.js

Fix for duplicate team names that aren't synced correctly

Fix teamsync issue for mixed teams

---

views/rebbl/team/player.pug

Fix for players that don't show coloured name correctly eg: https://rebbl.net/rebbl/team/2526696

Update coloured name regex

---

lib/LeagueService.js

Added new function for handling/combine division standings that are spread over multiple in-game diviisions.

Improved datahandling

---

lib/Rampup.js

THis way rerolled team get picked up over old teams

Fixed sorting for rampup

---

areas/account/account.js
lib/accountService.js
views/account/sublayout.pug
views/account/trophies.pug
views/rebbl/coach/trophies.pug
views/rebbl/league/index.pug

Added possibility to for a coach to choose what trophy to put on display

Choose trophy

---

lib/LeagueService.js
views/rebbl/league/index.pug

All leagues standing now include SoS calculation, but only displayed for Eurogamer open

Added SoS calculation

---

areas/api/v1/cripple.js
areas/api/v1/signups.js
areas/signup/signup.js
lib/signupService.js
views/signup/overview.pug
views/signup/signup-confirmed-greenhorn.pug
views/signup/signup-confirmed-oi.pug
views/signup/signup-existing.pug
views/signup/signup-new-coach.pug
views/signup/signup-rampup.pug
views/signup/signup-reroll.pug
views/signup/signups.pug

You who read this ping, wait 5 minutes for the site to get back up.
Also, no Davids!
(I hope)

Signups are open

---

areas/api/v1/signups.js
lib/LeagueService.js
lib/signupService.js
views/signup/signups.pug

Improved league sync
Fixed signup issue putting people in Big O

Signup Improvement

---

lib/DataService.js
lib/crippleService.js
lib/teamservice.js
public/styles/knockout.css
server.js
views/rebbl/index.pug
views/rebbl/playoffs/knockout.pug
views/rebbl/playoffs/knockouttemplate.pug
views/rebbl/playoffs/knockouttemplaterev.pug
views/rebbl/team/player.pug

corrected teams stats that got wiped

Moving teams & players to  mongo DB

---

views/rebbl/playoffs/knockouttemplate.pug
views/rebbl/playoffs/knockouttemplaterev.pug

https://rebbl.net/signup/counter - for you streamers

Hide admin teams in playoff bracket

---

lib/signupService.js
lib/teamservice.js
views/account/account.pug

https://github.com/majorbyte/rebbl/commit/ea44a3fb2f7dc002ebb22861c1625a3e2fe61439

Fixed conference determination for Eurogamers

---

lib/MaintenanceService.js

league caching went sour

---

areas/rebbl/coach.js

So it returns a complete match over first match

Modified regexp for searching cocaces

---

lib/RedditService.js

Admin Unplayed Games

---

lib/LeagueService.js
lib/RedditService.js
routes/rebbl/coach.js

"I'll use Regular Expression"
Now you've got two problems

Matching whole coachnames

---

README.md
lib/MaintenanceService.js
routes/admin/user.js
routes/api/v1/admin/unplayed.js
views/admin/unplayed/index.pug
views/admin/user/user.pug

 For <@271855364645847041> 

---

README.md
lib/DataService.js
routes/api/v2/api.js
routes/api/v2/division.js
routes/api/v2/match.js
routes/api/v2/standings.js
routes/rebbl/match.js
views/rebbl/coach/teams.pug
views/rebbl/standings/index.pug
views/rebbl/team/team.pug

 division and match endpoint added 

---

lib/MaintenanceService.js
views/rebbl/team/team.pug

Team page was not storing player types in local storage
League init was not doing it's job refreshing fixtures.

Teampage and league init bug fix

---

routes/api/v2/bloodbowl.js
routes/api/v2/division.js
routes/api/v2/league.js
routes/api/v2/match.js
routes/api/v2/standings.js
routes/api/v2/team.js

This way proper Content-Type Headers are sent

Using res.json over res.status(200).send()

---

lib/LeagueService.js
routes/rebbl/coach.js

Now I hope I really only have two problems left.

escaping regex

---

views/rebbl/index.pug

Now it's not just the logo that links to rebbl or rebbrl

Added links to landing page

---

lib/MaintenanceService.js
package-lock.json
package.json
routes/api/v2/division.js
server.js

- added a slim option
- Added gzip compression for requests

Added slim version of division fixtures

---

package-lock.json
package.json
routes/cripple/match.js
routes/rebbl/match.js
server.js
views/no-cache-sub-layout.pug

- Remove compression stuff 
- Added Home for navigation
- Bugfix for skilldescriptions

QOL improvements

---

apidoc.json
package-lock.json
package.json
server.js

Go to https://rebbl.net/api-docs/

Added api documentation

---

routes/api/v2/team.js
views/rebbl/team/team.pug

Probably will remove coach details matches.

Testing with matches on teams page

---

lib/ConfigurationService.js
lib/DataService.js
routes/api/v2/trophies.js
views/rebbl/league/index.pug
views/rebbl/match/match.pug
views/rebbl/standings/index.pug

- Fixed depracated function calls from mongodb driver 
- Added challenger cup

 Added challenger cup 

---

views/account/match.pug

Previously would only show the first link
Refactored the date to be gotten from the datepicker-input

Fix calendar link when there are multiple matches to be scheduled

---

views/cripple/standings.pug

it's 7 + best stunty, not just top 8

Changed cutoff for cripple

---

lib/ConfigurationService.js
lib/DataService.js
lib/LeagueService.js
lib/MaintenanceService.js
routes/maintenance/maintenance.js
routes/rebbl/league.js
views/rebbl/index.pug
views/rebbl/standings/index.pug

Better matching on coach name 
Fixed issue where team name is a number 
Minors And Upstarts moved to seasons

 Minors And Upstarts moved to seasons 

---

lib/ConfigurationService.js
lib/DataService.js
lib/apiService.js
routes/admin/admin.js
routes/admin/board.js
routes/api/v1/admin/admin.js
routes/api/v1/admin/board.js
views/admin/board/index.pug

Admin functionality added

---

views/admin/board/index.pug

return of coach is not always an array

Make return an array

---

lib/CyanideService.js
lib/MaintenanceService.js

Contest will now try to get 3 times upon failure, hopefully reducing the amount of contests. Also enabled all logging for contest, to see how many timeouts occur, and if trying 3 times helps

Fixed admin unplayed games

---

views/clan/matchup.pug
views/clan/schedule.pug

accounting for unknown reddit accounts

Corrected schedule algorithm,

---

lib/CyanideService.js
public/styles/style.css

Now every call gets 3 tries, with 5s delay inbetween

generalized Cyanide API call

---

routes/admin/admin.js
routes/admin/clan.js
routes/api/v2/clan.js
views/admin/clan/index.pug
views/admin/layout.pug
views/clan/clan.pug
views/clan/matchup.pug
views/clan/schedule.pug

Also added admin interface for managing used powers

Added used powers

---

routes/admin/clan.js
routes/api/v2/clan.js
views/admin/clan/index.pug

Add tooling for changings scores in clan

---

lib/ClanService.js
lib/LeagueService.js
routes/account/account.js
routes/api/v1/upcoming.js
routes/clan/clan.js
routes/maintenance/maintenance.js
routes/routes.js
views/clan/matchup.pug
views/clan/standings.pug

Also, clan matches should appear on /account/match, though, this only works when a game is started

Clan Standings

---

lib/LeagueService.js
views/clan/matchup.pug

Fixed minor issues

---

routes/api/v2/clan.js

No longer required to be logged in to check clan

---

routes/api/v1/cripple.js
routes/api/v1/playoffs.js
routes/api/v1/signups.js
routes/api/v1/standings.js
routes/api/v1/upcoming.js
routes/bloodbowl/bloodbowl.js
routes/cripple/match.js
routes/rebbl/coach.js
routes/rebbl/division.js
routes/rebbl/league.js
routes/rebbl/match.js
routes/rebbl/playoffs.js
routes/rebbl/rebbl.js
routes/rebbl/standings.js
routes/rebbl/stunty.js
routes/rebbl/team.js
routes/routes.js
routes/signup/signup.js

Change all the caching to default 10 minutes

---

routes/api/v2/clan.js

Using collator for comparisons

---

lib/DataService.js
routes/api/v2/clan.js
views/admin/clan/index.pug
views/clan/matchup.pug
views/rebbl/match/player.pug
views/rebbl/team/player.pug
views/rebbl/team/team.pug

Now also visible which player got EIC:ed in clan

Improved registration of EIC for admins

---

routes/api/v2/clan.js

Also corrected mistake with cas_state and cas_sustained

Fixed wrong comparison in clan matchups

---

routes/bloodbowl/bloodbowl.js
views/bloodbowl/legendaryplayers.pug
views/bloodbowl/starplayers.pug
views/rebbl/upcoming/index.pug
views/rebbl/upcoming/ongoing.pug

Added filter to Legendary Players,
Added filter to ongoing games,
Added proper menu to the pages linked on the landing page

QOL update for some pages

---

views/admin/clan/index.pug

this way heroto can't fuck up shit anymore

New Blood now correctly closes after using

---

lib/MaintenanceService.js

I think this was the cause to teams like my own having a mismatch i games played and actual games played
closes #501

Don't parse matches when initializing a league

---

lib/MaintenanceService.js
views/account/account.pug

Fixed issue with admin-refresh of competitions

Added clear local storage option on account

---

lib/ClanService.js
routes/api/v2/clan.js
views/admin/clan/index.pug
views/rebbl/coach/details.pug

Added twitch to coach details page

added substitute coach function for clan

---

routes/api/v2/account.js
views/rebbl/standings/index.pug

I got tired of scrolling.
For Rebbl main league (sorry rebbrlers) standgins should autoscroll to you division.
Unless you maybe changed division, or.. as I realize just as I type this up, are coming from rampup

little QOL

---

lib/DataService.js

I guess upstarts is started as swiss, but with not all the tickets accepted

Need to handle swiss without opponents.

---

views/rebbl/division/index.pug
views/rebbl/division/matches.pug
views/rebbl/standings/index.pug

Proper scrolling to standings of you div

---

routes/api/v1/oi.js
routes/api/v2/clan.js

inactive teams were not filtered out

Fixed bug for schedule overview

---

routes/api/v2/bloodbowl.js
views/bloodbowl/legendaryplayers.pug

Link is found on the player popup

Added last match played for legendary players

---

routes/api/v1/upcoming.js
views/rebbl/upcoming/ongoing.pug

also filtered out the hanging games

Fixed duplication of ongoing games

---

lib/DataService.js
lib/signupService.js
routes/signup/signup.js
views/signup/overview.pug
views/signup/signup-confirmed-greenhorn.pug
views/signup/signup-confirmed-oi.pug
views/signup/signup-rampup.pug
views/signup/signup-reroll.pug
views/signup/signups.pug

Following signups are open:
- Rebbl Season 14
- College Season 11
- Minors Season 10
- Greenhorn Cup
- Off-Season International

Opening the flood gates

---

lib/CampingService.js

there was a coached that broke the scripts, and big O doesn't follow the `Season 13 - Division X` -pattern

Tweaks for Summer Camp

---

lib/ClanService.js
routes/maintenance/maintenance.js

1: Games vs AI are disregarded
2: Games vs Admin teams are now correctly handled

Fixed clan standings calculation

---

routes/maintenance/maintenance.js

typical works-on-my-machine issue

Correct typo

---

routes/api/v2/standings.js

Snn competitions should be handled/named as Season mm)

Better Snn handling

---

views/no-cache-sub-layout.pug

Added Tooltips to icons on main page.

Main Page: Added tooltips to different league icons

---

lib/apiService.js
lib/signupService.js
robots.txt
routes/signup/signup.js
views/signup/overview.pug
views/signup/signup-rampup.pug

Opening RAMPUP signups

---

routes/api/v2/account.js

This occurred when an [admin] team was in your division

Fixed an issue where you wouldn't get data

---

lib/ClanService.js
lib/DraftService.js
views/clan/matchup.pug

Showing unstarted matches.
Only showing Start Games button when there are actual games to be start, according to rebbl.net that is
Changed color of draft button when draft has been completed.

Clan Improvements

---

routes/api/v1/upcoming.js

The days of Crusty Plush vs We're Drunk are over. sad times.

Fixed ongoing games

---

routes/rebbl/rebbl.js

/{league}/team/* -> /team/*
/{league}/coach/* -> /coach/*

Added permanent redirects

---

routes/signup/signup.js

There was a word missing in the Application Form. I added it.

Fix typo in application form

---

lib/DraftService.js
routes/signup/signup.js
views/signup/signup-new-coach-rebbrl.pug
views/signup/signup-new-coach.pug

Now informing coaches about their wrong coachname

---

public/styles/style.css
public/styles/style.dark.css
views/coach/details.pug
views/no-cache-sub-relayout.pug
views/rebbl/index.pug
views/rebbl/league/rampup.pug
views/signup/signups.pug

- mobile update for frontpage and rampup
- coach details mobile fix
- mobile friendly signups list

Mobile friendly signups, coach view, rampup and frontpage (#742)

---

lib/LeagueService.js
routes/api/v1/admin/divisions.js
views/admin/unplayed/index.pug

really need to stop with this hardcoded stuff

Season 15 admin prep

---

lib/TicketService.js

Tickets can be moved around,

---

routes/api/v2/division.js

Only getting games less than 7 days old
Not trying to get admin concedes

Improved query for getting unsaved games

---

routes/api/v1/signups.js

* Mark competition as incomplete when 1-4 games are played
* Add sign up date to json payload

Add signup date to api json (#805)

---

routes/signup/signup.js

Allow rookie confirmations for reserves

Add rookie confirm route back (#810)

---

routes/api/v2/clan.js
views/clan/clan.pug
views/clan/matchup.pug

bumped version to 11 to match season 11

Added stunty power descriptios

---

lib/ClanService.js
routes/api/v2/draft.js
views/admin/clan/index.pug

there were some issues with the draft tool

More Clan fixes

---

package.json
routes/account/account.js
routes/account/auth.js
views/account/account.pug
views/coach/details.pug
views/coach/matches.pug
views/coach/teams.pug
views/coach/trophies.pug

Just an FYI, this disables text input on the Discord textfield. You'll need implement a Discord App and pull the Client Id and Client Secret put then in env variables.  Same with the discord callback URL.

Add Discord oauth2 support

---

lib/ChaosService.js
lib/ChristmasCracker.js
lib/DataService.js
lib/HugeService.js
lib/LeagueService.js
lib/OffSeasonService.js
routes/api/v2/camping.js
routes/maintenance/maintenance.js
server.js
views/nav.pug

Implemented  HJ Memorial Ladder collection and calculation

Redone match collection for offseason competitions

---

lib/HugeService.js
views/rebbl/huge.pug

Added additional 'tiebreakers' to HJ Memorial Ladder

Fixed a display issue for huge ladder.

---

lib/DraftService.js

Reddit is rate limiting Griff for some reason.
I guess short bursts within a second aren't cool anymore, because the ratelimit values where well within limit.
(limited while at 4/500 requests limit)

Don't upset Snoo

---

routes/api/v2/clanBuilding.js
views/clan/build.pug
views/clan/scripts/member.pug
views/clan/scripts/player.pug
views/clan/scripts/team.pug
views/clan/templates/clanTemplate.pug

Case-sensitivity issue with member/coach names
Niggles need not to be filtered out
Fixed the tiers for S13, but not the Tax/rebates for the changed races

FIxes: Stats use the wrong value for cost calculations
